src/Entity/Usuario.php
<?php

namespace App\Entity;

use App\Repository\UsuarioRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UsuarioRepository::class)
 */
class Usuario implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;


    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $nombre;

    /**
     * @ORM\Column(type="boolean")
     */
    private $estado;

    /**
     * @ORM\Column(type="datetime")
     */
    private $fecha_activacion;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $correo;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $token;

    /**
     * @ORM\ManyToOne(targetEntity=UsuarioTipo::class, inversedBy="usuarios")
     * @ORM\JoinColumn(nullable=false)
     */
    private $usuarioTipo;

   
    /**
     * @ORM\OneToMany(targetEntity=UsuarioCuenta::class, mappedBy="usuario")
     */
    private $usuarioCuentas;

    /**
     * @ORM\OneToMany(targetEntity=Privilegio::class, mappedBy="usuario", orphanRemoval=true)
     */
    private $privilegios;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $empresaActual;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $fechaNoDisponible;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $whatsapp;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $telefono;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $rut;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $direccion;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $sexo;

    /**
     * @ORM\ManyToOne(targetEntity=UsuarioCategoria::class, inversedBy="usuarios")
     */
    private $categoria;

    /**
     * @ORM\ManyToOne(targetEntity=UsuarioStatus::class, inversedBy="usuarios")
     */
    private $status;

    
    /**
     * @ORM\ManyToOne(targetEntity=UsuarioTipoDocumento::class, inversedBy="usuarios")
     */
    private $tipoDocumento;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $color;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $passwordAnt;

    /**
     * @ORM\OneToMany(targetEntity=UsuarioUsuariocategoria::class, mappedBy="usuario", orphanRemoval=true)
     */
    private $usuarioUsuariocategorias;

    
    /**
     * @ORM\OneToMany(targetEntity=Importacion::class, mappedBy="usuarioCarga")
     */
    private $importacions;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $lunes;

    /**
     * @ORM\Column(type="time", nullable=true)
     */
    private $lunesStart;

    /**
     * @ORM\Column(type="time", nullable=true)
     */
    private $lunesEnd;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $martes;

    /**
     * @ORM\Column(type="time", nullable=true)
     */
    private $martesStart;

    /**
     * @ORM\Column(type="time", nullable=true)
     */
    private $martesEnd;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $miercoles;

    /**
     * @ORM\Column(type="time", nullable=true)
     */
    private $miercolesStart;

    /**
     * @ORM\Column(type="time", nullable=true)
     */
    private $miercolesEnd;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $jueves;

    /**
     * @ORM\Column(type="time", nullable=true)
     */
    private $juevesStart;

    /**
     * @ORM\Column(type="time", nullable=true)
     */
    private $juevesEnd;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $viernes;

    /**
     * @ORM\Column(type="time", nullable=true)
     */
    private $viernesStart;

    /**
     * @ORM\Column(type="time", nullable=true)
     */
    private $viernesEnd;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $sabado;

    /**
     * @ORM\Column(type="time", nullable=true)
     */
    private $sabadoStart;

    /**
     * @ORM\Column(type="time", nullable=true)
     */
    private $sabadoEnd;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $domingo;

    /**
     * @ORM\Column(type="time", nullable=true)
     */
    private $domingoStart;

    /**
     * @ORM\Column(type="time", nullable=true)
     */
    private $domingoEnd;

    /**
     * @ORM\OneToMany(targetEntity=UsuarioNoDisponible::class, mappedBy="usuario")
     */
    private $usuarioNoDisponibles;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $sobrecupo;

    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private $lotes = [];


    
    public function __construct()
    {
        $this->usuarioCuentas = new ArrayCollection();
        $this->privilegios = new ArrayCollection();
        $this->usuarioUsuariocategorias = new ArrayCollection();
        $this->importacions = new ArrayCollection();
        $this->usuarioContratos = new ArrayCollection();
        $this->usuarioNoDisponibles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        //$roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[]= 'ROLE_USER';

        return $roles;
    }

   

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getEstado(): ?bool
    {
        return $this->estado;
    }

    public function setEstado(bool $estado): self
    {
        $this->estado = $estado;

        return $this;
    }

    public function getFechaActivacion(): ?\DateTimeInterface
    {
        return $this->fecha_activacion;
    }

    public function setFechaActivacion(\DateTimeInterface $fecha_activacion): self
    {
        $this->fecha_activacion = $fecha_activacion;

        return $this;
    }

    public function getCorreo(): ?string
    {
        return $this->correo;
    }

    public function setCorreo(string $correo): self
    {
        $this->correo = $correo;

        return $this;
    }

    public function getToken(): ?string
    {
        return $this->token;
    }

    public function setToken(?string $token): self
    {
        $this->token = $token;

        return $this;
    }

    public function getUsuarioTipo(): ?UsuarioTipo
    {
        return $this->usuarioTipo;
    }

    public function setUsuarioTipo(?UsuarioTipo $usuarioTipo): self
    {
        $this->usuarioTipo = $usuarioTipo;

        return $this;
    }

    public function __toString()
    {
        return $this->nombre;
    }

    /**
     * @return Collection|UsuarioCuenta[]
     */
    public function getUsuarioCuentas(): Collection
    {
        return $this->usuarioCuentas;
    }

    public function addUsuarioCuenta(UsuarioCuenta $usuarioCuenta): self
    {
        if (!$this->usuarioCuentas->contains($usuarioCuenta)) {
            $this->usuarioCuentas[] = $usuarioCuenta;
            $usuarioCuenta->setUsuario($this);
        }

        return $this;
    }

    public function removeUsuarioCuenta(UsuarioCuenta $usuarioCuenta): self
    {
        if ($this->usuarioCuentas->removeElement($usuarioCuenta)) {
            // set the owning side to null (unless already changed)
            if ($usuarioCuenta->getUsuario() === $this) {
                $usuarioCuenta->setUsuario(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Privilegio[]
     */
    public function getPrivilegios(): Collection
    {
        return $this->privilegios;
    }

    public function addPrivilegio(Privilegio $privilegio): self
    {
        if (!$this->privilegios->contains($privilegio)) {
            $this->privilegios[] = $privilegio;
            $privilegio->setUsuario($this);
        }

        return $this;
    }

    public function removePrivilegio(Privilegio $privilegio): self
    {
        if ($this->privilegios->removeElement($privilegio)) {
            // set the owning side to null (unless already changed)
            if ($privilegio->getUsuario() === $this) {
                $privilegio->setUsuario(null);
            }
        }

        return $this;
    }

templates/administrador_cuentas/_delete_form.html.twig
<form method="post" action="{{ path('administrador_cuentas_delete', {'id': id_usuario}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ usuario.id) }}">
    <button class="btn btn-danger"><span class="fas fa-trash"></span></button>
</form>

templates/administrador_cuentas/_form.html.twig
{{ form_start(form) }}

	
<div class="card">
	<div class="card-body">

		<section>	
			<div class="row">
				<div class="col-sm-6 col-md-3">
					<small class="text-muted">{{nombreCuenta|default('Compañia')}} *</small>
				
					<select name="cboEmpresa[]" class="select2" multiple="multiple" data-placeholder="Selecciona compañias" style="width: 100%;" required>
						<option></option>
						{% for cuenta in cuentas %}
							<option value="{{cuenta.id}}"
							{% if cuentas_sel is defined %}
								{% for usuarioCuent in cuentas_sel %}
									{% if usuarioCuent.cuenta.id==cuenta.id %}
										selected
									{% endif %}
								{% endfor %}
							{% endif %}
							>{{cuenta.nombre}}</option>
						{% endfor %}}
					</select>
				</div>
				<div class="col-sm-6 col-md-6">
					<small class="text-muted">Nombre</small>
					{{form_row(form.nombre,{'label':false,'attr':{'class':'form-control','maxlength':'50'}})}}
				</div>
				
				<div class="col-sm-6 col-md-3">
					<small class="text-muted">Rut</small>
					{{form_row(form.rut,{'label':false,'attr':{'class':'form-control','placeholder':'Rut'}})}}
					
				</div>
				<div class="col-sm-6 col-md-3">
				<small class="text-muted">Correo</small>
					{{form_row(form.correo,{'label':false,'attr':{'class':'form-control'}})}}
				</div>
				<div class="col-sm-6 col-md-3">
					<small class="text-muted">Telefono</small>
					{{form_row(form.telefono,{'label':false,'attr':{'class':'form-control'}})}}
					
				</div>
				<div class="col-sm-6 col-md-3">
					<small class="text-muted">Whatsapp</small>
					{{form_row(form.whatsapp,{'label':false,'attr':{'class':'form-control'}})}}
					
				</div>
				<div class="col-sm-6 col-md-3">
					<small class="text-muted">Dirección</small>
					{{form_row(form.direccion,{'label':false,'attr':{'class':'form-control'}})}}
					
				</div>
				<div class="col-sm-6 col-md-3">
					<small class="text-muted">Sexo</small>
					{{form_row(form.sexo,{'label':false,'attr':{'class':'form-control'}})}}
					
				</div>

				
				<div class="col-sm-6 col-md-3">
					<small class="text-muted">Colaborador *</small>
					
					<select name="cboTipoDocumento" class="form-control" required>
						<option></option>
						{% for tipo_documento in tipo_documentos %}
							<option value="{{tipo_documento.id}}"
							{% if usuario.tipoDocumento.id is defined %}

									{% if  usuario.tipoDocumento.id ==tipo_documento.id %}
										selected
									{% endif %}
							
							{% endif %}
							>{{tipo_documento.nombre}}</option>
						{% endfor %}}
					</select>
				</div>
			</div>
		</section>
		<section>
			<div class="row">
				<div class="col-12">
				<h1>Datos de Sesión</h1>
				</div>
				<div class="col-sm-6 col-md-3">
					<small class="text-muted">Usuario</small>
					{{form_row(form.username,{'label':false,'attr':{'class':'form-control','placeholder':'Usuario'}})}}
				</div>
				<div class="col-sm-6 col-md-3">
					<small class="text-muted">Password</small>
					{{form_row(form.password,{'label':false, 'attr':{'class':'form-control', 'placeholder':'******' ,'type':'password','required':false}})}}
					{{form_row(form.passwordAnt,{'label':false, 'attr':{'class':'form-control', 'placeholder':'******' ,'type':'password','required':false}})}}
				</div>
			</div>
		</section>
	</div>
	<div class="card-footer">
		<button class="btn btn-primary">{{ button_label|default('Crear') }}</button>
	</div>
</div>

    
	<script>
		$(function () {
			//Initialize Select2 Elements
			$('.select2').select2();
			
		});
	</script>
{{ form_end(form) }}

templates/administrador_cuentas/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{pagina|default('Agendadora')}}{% endblock %}

{% block body %}
	
    {{ include('administrador_cuentas/_form.html.twig', {'button_label': 'Modificar'}) }}

   
    
{% endblock %}

templates/administrador_cuentas/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{pagina}}{% endblock %}

{% block body %}
<div class="card">
        <div class="card-header">
            Listado
        </div>
        <div class="card-body">
        
        {% if modo == 1 %}
            <a href="{{path('administrador_cuentas_new')}}" class="btn btn-primary" id="btn-agregar"><i class="fas fa-plus"></i></a>
            <a href="{{path('administrador_cuentas_index',{'modo':'trash'})}}" class="btn btn-danger"><i class="fas fa-trash"></i> Usuarios Eliminados</a>
        {% else %}
            <a href="{{path('administrador_cuentas_index')}}" class="btn btn-success"><i class="fas fa-trash-restore"></i> Usuarios Activos</a>
        {% endif %}
            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Usuario</th>
                        <th>Nombre</th>
                        <th>Tipo Usuario</th>
                        <th>Estado</th>
                        <th>Fecha alta</th>
                        <th>Correo</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                {% for usuario in usuarios %}
                    <tr>
                        <td>{{ usuario.id }}</td>
                        <td>{{ usuario.username }}</td>
                        <td>{{ usuario.nombre }}</td>
                        <td>{{ usuario.usuarioTipo.nombre }}</td>
                        <td>{{ usuario.estado ? 'Activo' : 'Deshabilitado' }}</td>

                        <td>{{ usuario.fechaActivacion ? usuario.fechaActivacion|date('Y-m-d H:i:s') : '' }}</td>
                        <td>{{ usuario.correo }}</td>
                        
                        <td>
                            <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
                                {% if modo == 1 %}
                                <a href="{{path('administrador_cuentas_edit',{'id':usuario.id})}}" class="btn btn-secondary"><spam class='fas fa-edit'></spam></a>
                                {{ include('administrador_cuentas/_delete_form.html.twig',{'id_usuario':usuario.id}) }}
                                <a href="{{path('privilegio_index',{'id':usuario.id})}}" class="btn btn-warning" > <i class="fas fa-share-alt"></i></a>
                                {% else %}
                                <a href="{{path('administrador_cuentas_restore',{'id':usuario.id})}}" class="btn btn-success"><spam class='fas fa-trash-restore'></spam></a>

                                {% endif %}
                            </div>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="8">No hay Usuarios</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="card-footer">
            <div class="navigation">
                {{ knp_pagination_render(usuarios,'@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig',{},{
                'position': 'centered',
                'rounded': true,
                }) }}
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="controles" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
        
          </div>
         
        </div>
      </div>
    </div>
    
{% endblock %}

templates/administrador_cuentas/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Administrador Cuentas{% endblock %}

{% block body %}
    <div class="card">
        <div class="card-body">
    {{ include('administrador_cuentas/_form.html.twig') }}

        </div>
    </div>
{% endblock %}

templates/administrador_cuentas/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Usuario{% endblock %}

{% block body %}
    

<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-sm-6 col-md-3">
				<small class="text-muted">Empresa *</small>
				<label></label>
			</div>
			<div class="col-sm-6 col-md-6">
				<small class="text-muted">Nombre</small>
				<label>{{usuario.nombre}}</label>
			</div>
			<div class="col-sm-6 col-md-3">
				<small class="text-muted">Rut</small>
				<label>{{usuario.rut}}</label>
				
			</div>
			<div class="col-sm-6 col-md-3">
			<small class="text-muted">Correo</small>
				<label>{{usuario.correo}}</label>
			</div>
			<div class="col-sm-6 col-md-3">
				<small class="text-muted">Telefono</small>
				<label>{{usuario.telefono}}</label>
				
			</div>
			<div class="col-sm-6 col-md-3">
				<small class="text-muted">Whatsapp</small>
				<label>{{usuario.whatsapp}}</label>
				
			</div>
			<div class="col-sm-6 col-md-3">
				<small class="text-muted">Dirección</small>
				<label>{{usuario.direccion}}</label>
				
			</div>
			<div class="col-sm-6 col-md-3">
				<small class="text-muted">Sexo</small>
				<label>{{usuario.sexo}}</label>
				
			</div>
			
            <div class="col-sm-6 col-md-3">
				<small class="text-muted">Usuario</small>
				<label>{{usuario.username}}</label>
				
			</div>
			    

        </div>

    </div>
</div>

{% endblock %}